import  '@/app/ui/global.css'
import { inter } from '@/app/ui/fonts'

import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Welcome to the NextJS Dashboard App',
    description: 'Generated by coryphaeus hands.',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`} >{children}</body>
    </html>
  );
}
